### ISSUE TITLE
Any plan to support WebAssembly?

### ISSUE THREAD

**Issue by CBenoit** [Eugeny/russh#155]
Hi,

Out of curiosity, is there any plan or desire to make russh more WebAssembly-friendly?

Currently I see a few dependencies that can’t be used in WebAssembly: tokio, libc and winapi.
Changing this might be significant work.

Is it something on your radar yet? Would you accept somewhat significant contributions towards this goal?

**Comment by CBenoit** [comment]
The use case is to build SSH web clients and SSH session web players.

As you say, there is no way to use TCP sockets. That’s why the data transport should not be hard-coded the way it currently is (tokio’s TcpStream). Ideally, it should be possible to swap the TCP socket with a WebSocket or a file stream instead. (Ability to to replace the TCP stream by a file stream would be useful to build a native web player as well.)

Note that we can perform an actual SSH session using a WebSocket by using a proxy mapping WebSocket to TCP.

**Comment by Eugeny** [comment]
russh doesn't include any I/O that is strictly necessary (it can run against a generic AsyncRead + AsyncWrite stream), but it needs basic async primitives like task spawning and sleeping - how is this usually sorted out in rust+wasm?

**Comment by CBenoit** [comment]
Tasks may be spawned using [`spawn_local`](https://docs.rs/wasm-bindgen-futures/latest/wasm_bindgen_futures/fn.spawn_local.html) and sleeping can be implemented [on top of `setTimeout`](https://users.rust-lang.org/t/async-sleep-in-rust-wasm32/78218/2) or by using [the `gloo_timers` crate](https://docs.rs/gloo-timers/latest/gloo_timers/#timeouts-as-futures). We could imagine building a light abstraction on top of this and select the correct implementation at compile-time.

Another approach is to provide a state machine to be instrumented by client code instead. This could be a lower-level crate on which we rebuild the current API.

Also, it is of note that tokio’s `AsyncRead` and `AsyncWrite` can’t be used when targeting WebAssembly. These traits are defined in the main `tokio` crate and the `tokio` crate itself can’t be compiled to WebAssembly. [`futures-io` traits](https://crates.io/crates/futures-io) may be used instead. [`tokio_util` is providing a compat layer](https://docs.rs/tokio-util/0.7.7/tokio_util/compat/index.html) to get a tokio AsyncRead/AsyncWrite from a futures AsyncRead/AsyncWrite as necessary.

For reference, in my projects I usually separate into several crates this way:
- foo-pdu: PDU encoding and decoding (no I/O, read from `&[u8]`, write to `&mut [u8]` or `&mut Vec<u8>`, trivial to fuzz),
- foo-session: state machine to drive a connection sequence and session (no I/O, not too hard to fuzz),
- foo-session-async: provides Futures wrapping the session state machine conveniently,

All the platform-specific code is a thin layer in the `foo-session-async` crate. It’s also easy to build against `foo-session` and _not_ use async at all. Problem is, converting Rust code using async / await keywords to a state machine is no fun so that’s probably not an option in this case.

**Comment by Eugeny** [comment]
This would be too much of a refactor for me to invest my own time unfortunately, but I'm happy to merge incremental PRs if anybody's down to work on it.

**Comment by reesericci** [comment]
Any updates on this? Looking to use this in-browser with a WebSocket transport as well

**Comment by CBenoit** [comment]
@reesericci code from my colleague @irvingoujAtDevolution was merged, and we are currently using russh in the web browser! Actually, we can close the issue with #349

**Comment by reesericci** [comment]
Amazing!

**Comment by reesericci** [comment]
Hey y'all, sorry for the necropost - would it be possible to get an example on how to use this? Trying to convert one of the tokio examples and getting lost.
