### ISSUE TITLE
Shutdown ssh server

### ISSUE THREAD

**Issue by richterger** [Eugeny/russh#317]
Hi, I have the need to start and stop the ssh server, within the same program. While starting the ssh server works as excepted, I have found no way to shutdown the ssh server, other than ending the whole program. Is there a way to shutdown the ssh server?

If not I would create a pull request for shuting down. The idea is to add it to the loop/select! in run_on_socket and also in Session::run.

Any thougths on this?

Regards Gerald

**Comment by Eugeny** [comment]
You can stop the server by simply not running it any more:

```rust
let (stop_tx, mut stop_rx) = tokio::sync::mpsc::unbounded_channel();
let server_fut = server.run_on_address(config, ("0.0.0.0", 22));

tokio::select! {
    _ = server_fut => (),
    Some(_) = stop_rx.recv() => (),
}
```

... somewhere else:

```rust
stop_tx.send(());
```

**Comment by richterger** [comment]
That works perfectly. Thanks!
