### ISSUE TITLE
Prove/ensure crypto safety

### ISSUE THREAD

**Issue by mbrodala** [Eugeny/russh#327]
I am currently evaluating options to improve our SSH access management. Here I stumbled upon [Warpgate](https://github.com/warp-tech/warpgate) and while it sounds like it could fit my needs (and even go beyond) I am a little concerted about the crypto-component which seems to be russh.

Specifically it looks like there are not as many automated tests as one would expect from a crypto-library which a) prove that the implementation is as fault-free as possible, b) showcases how edge-cases are handled and c) prevents regressions.

Am I simply missing something here? Disclaimer: I have no knowledge at all about Rust and its ecosystem so I may simply misunderstand how everything works.

**Comment by Eugeny** [comment]
Hi, russh is purely a protocol implementation and does not implement its own cryptography, but rather instead relies on the libraries from the RustCrypto suite and OpenSSL.

**Comment by mbrodala** [comment]
That would explain why I was unable to find relevant crypto-related tests. Thanks for the clarification!
