### ISSUE TITLE
expected type, found variant None

### ISSUE THREAD

**Issue by bu420** [Eugeny/russh#335]
All of a sudden russh stopped working for me. 
I am using v0.45.0.

Error on line 148 in server/mod.rs:
`expected type, found variant None`

![image](https://github.com/user-attachments/assets/8117a8a9-cc40-448e-bb1e-d96b9bad68f9)

**Comment by Eugeny** [comment]
Did you edit the file manually? It's not in the code: https://github.com/Eugeny/russh/blob/main/russh/src/server/mod.rs#L148
