### ISSUE TITLE
Add Support for ssh -D (SOCKS Proxy)

### ISSUE THREAD

**Issue by namegorm** [Eugeny/russh#340]
I would like to propose the addition of support for the ssh -D functionality (dynamic port forwarding / SOCKS proxy) to the Russh library. Currently, Russh supports static port forwarding (-L, -R), which is highly valuable for secure tunneling. However, the addition of SOCKS proxy support (similar to OpenSSH's -D flag) would make this library more versatile for users who rely on dynamic routing of network traffic through an SSH tunnel.

**Comment by cougarwww** [comment]
channel_open_direct_tcpip for ssh -L/-D
tcpip_forward for ssh -R

**Comment by Eugeny** [comment]
Actual SOCKS handling is outside of this library's scope. Accept connections on a local port, use any socks server crate and open the connections to your destinations via `channel_open_direct_tcpip` like @cougarwww said.

**Comment by Eugeny** [comment]
(This could be an idea for a small companion library but not for `russh` itself)
