### ISSUE TITLE
Strict StrictKeyExchangeViolation when kex re-exchanging with OpenSSH

### ISSUE THREAD

**Issue by blacktemplar** [Eugeny/russh#358]
I am working on a local port forwarding implementation using russh and I found the following problem:

russh clients do strict kex checks by default (`kex::EXTENSION_OPENSSH_STRICT_KEX_AS_CLIENT` is part of the default `Config::preferred::kex) but it seems like [OpenSSH servers allow only strict kex checks on preauth](https://github.com/openssh/openssh-portable/blob/67a115e7a56dbdc3f5a58c64b29231151f3670f5/PROTOCOL#L147C44-L149C60).

This means that on initial negotation everything works out, both parties do strict kex checks, but when a kex re-exchanging happens (in my case after some certain amount of data got transferred) the client terminates because of a strict key exchange violation (it expects strict kex but the server sends no strict kex since it is not preauth).

I think to fix this we should do strict kex checks only the first time and not on re-exchanges.

For now the only way to fix this on my side was specifying `Config::preferred::kex` myself and removing the `kex::EXTENSION_OPENSSH_STRICT_KEX_AS_CLIENT` key.

**Comment by Eugeny** [comment]
Did they change it recently? I've tested with `openssh-server-1:8.4p1-5+deb11u3` and it sends `kex-strict-s-v00@openssh.com` on rekey. I'll fix it of course, just wanted to know what to test with.
