### ISSUE TITLE
Release 0.46.0

### ISSUE THREAD

**Issue by qsantos** [Eugeny/russh#370]
The last release was from Aug 15. Since then, there were changes to the API. For instance, [`generate_ed25519`](https://docs.rs/russh-keys/0.45.0/russh_keys/key/enum.KeyPair.html#method.generate_ed25519) was made infallible, breaking the [echoserver example](https://github.com/Eugeny/russh/blob/main/russh/examples/echoserver.rs).

Would it be possible to release a 0.46.0 with these changes?

~~In passing, I noticed `0.46.0-beta.{1,2,3}` in the docs, but not the corresponding docs, making it harder to find out how old they are.~~ `0.46.0-beta.3` is from Aug 20.

**Comment by Eugeny** [comment]
There are a bunch of more significant and fresh API-breaking changes introduced by the migration from homebrew key handling code to RustCrypto's `ssh-key` crate, which I need to test some more before I release it, but I've released a `v0.46.0-beta`, so if you've got time feel free to give it a test :)

**Comment by Eugeny** [comment]
Upon further testing I decided to release v0.46 without it, ssh-key changes are in the master branch for now

**Comment by qsantos** [comment]
That's great, thanks!
