### ISSUE TITLE
Potential unsoundness in memcpy

### ISSUE THREAD

**Issue by lwz23** [Eugeny/russh#394]
I belive there is a unsound problem in 'memcpy' function https://github.com/Eugeny/russh/blob/ff95994945db593115dd0d663f8c41ecba945b9f/cryptovec/src/platform/wasm.rs#L17
```
pub fn memcpy(dest: *mut u32, src: *const u8, size: usize) {
    unsafe {
        // Convert dest to *mut u8 for byte-wise copying
        let dest_bytes = dest as *mut u8;

        // Use std::ptr::copy_nonoverlapping to copy the data
        std::ptr::copy_nonoverlapping(src, dest_bytes, size);
    }
}
```
**Why Unsoundness Can Occur**
1. Pointer Conversion:
dest is passed as a *mut u32 but is cast to *mut u8. This means the caller is expected to provide a valid *mut u32 pointer, but the function performs a u8-level byte-wise copy.
This violates the alignment guarantees of *mut u32, as u32 pointers must be properly aligned to 4 bytes. If dest is not correctly aligned, this operation leads to undefined behavior (UB).
2. Invalid Pointers:
If dest or src are null or invalid (e.g., dangling or pointing to memory not owned by the process), std::ptr::copy_nonoverlapping will invoke UB when trying to access these memory locations.
3. Out-of-Bounds Access:
size is passed without bounds checking. If size exceeds the memory available at either src or dest, it can lead to memory corruption or illegal memory access, causing UB.
4. Lack of Safety Contract:
The function is marked as safe (pub fn), but its correctness relies entirely on the caller ensuring:
dest is aligned correctly for *mut u32.
Both src and dest point to valid, non-overlapping memory regions.
size does not exceed the valid memory bounds of either region.

**Comment by lwz23** [comment]
ping?

**Comment by Eugeny** [comment]
@irvingoujAtDevolution could you take a look please?

**Comment by irvingoujAtDevolution** [comment]
I'll take a look

**Comment by irvingoujAtDevolution** [comment]
After quick search, memcpy is never used and can be removed safely, I'll just create a PR remove the function.
