### ISSUE TITLE
100% CPU usage after connection lost while sending large amount of data

### ISSUE THREAD

**Issue by PonyPC** [Eugeny/russh#401]
100% CPU usage after connection lost while sending large amount of data

The issue is in https://github.com/Eugeny/russh/blob/ff95994945db593115dd0d663f8c41ecba945b9f/russh/src/channels/io/tx.rs#L64

It won't triggle connection lost event.

**Comment by EpicEric** [comment]
Shouldn't this trigger an `Err(BrokenPipe)`? Or am I missing some other way that would lead to the condition being reached?

**Comment by PonyPC** [comment]
Nothing triggered. If you add a check like:
```
            if self.sender.is_closed() {
                return Poll::Ready((ChannelMsg::Eof, 0));
            }
```
It only mitigates the tcp las a connection lost event. But when you try it such as block the connection by using a firewall realtime rules, the CPU usage is still high until tcp timeout error. As it not sufficient on dealing with sending data, is there any other ways to eliminate this situation.

**Comment by PonyPC** [comment]
Nothing triggered. If you add a check like:
```
            if self.sender.is_closed() {
                return Poll::Ready((ChannelMsg::Eof, 0));
            }
```
It only mitigates the tcp has a connection lost event. But when you try it such as blocking the connection by using a firewall realtime rules, the CPU usage is still high until tcp timeout error. As it not sufficient on dealing with sending data, is there any other ways to eliminate this situation?
